accessKey           ="AKIAYDYGJFAERUKSQGEK"
secretKey           ="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"
region              ="ap-south-1"
lambdaname          ="Nihanth_lambda-aws-ec2-snapshot"
tagName             ="prod-servers"
tagValue            ="snapshot"