accessKey           =""
secretKey           =""
region              ="ap-south-1"
lambdaname          ="Nihanth_lambda-aws-ec2-snapshot"
tagName             ="prod-servers"
tagValue            ="snapshot"