accessKey           ="AKIAYDYGJFAERUKSQGEK"
secretKey           ="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"
region              ="ap-south-1"
lambdaname          ="lambda_nihanth-aws-ec2-start"
tagName             ="office-hours"
tagValue            ="ec-data-platform"
