accessKey           ="AKIAYDYGJFAEVRZFOXUI"
secretKey           ="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"
region              ="ap-south-1"
lambdaname          ="lambda-aws-ec2-start"
tagName             ="office-hours"
tagValue            ="ec-data-platform"